# Generated by Django 4.1.7 on 2023-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dateofbirth', models.DateField(null=True)),
                ('photo', models.CharField(max_length=250, null=True)),
                ('is_married', models.BooleanField()),
                ('memberships', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('P', 'Platinum')], default='G', max_length=1)),
            ],
        ),
    ]
