# Generated by Django 4.2 on 2023-05-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_Address',
            new_name='ShippingAddress',
        ),
    ]
