# Generated by Django 4.2.3 on 2023-08-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
