# Generated by Django 4.2.3 on 2023-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
