# Generated by Django 4.2.3 on 2023-08-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
